---
# PostgreSQL ping and connectivity test

- name: >
    Ping PostgreSQL server using non-default credentials and SSL
    registering the return values into the result variable for future use
  tags: [pg_ping]
  community.postgresql.postgresql_ping:
    login_db: postgres
    login_port: 54312
    login_host: 127.0.0.1
    login_user: dba_melih
    login_password: secure_password
 #   ca_cert: /root/root.crt
 #   ssl_mode: verify-full
  register: result
  # If you need to fail when the server is not available,
  # uncomment the following line:
  # failed_when: not result.is_available

# You can use the registered result with another task
- name: This task should be executed only if the server is available
  tags: [pg_ping]
  debug:
    msg: "PostgreSQL server is available and responding"
  when: result.is_available == true

- name: Display PostgreSQL server information
  tags: [pg_ping]
  debug:
    msg: |
      PostgreSQL Server Status:
      - Available: {{ result.is_available }}
      - Server Version: {{ result.server_version | default('N/A') }}
      - Connection Error Message: {{ result.conn_err_msg | default('N/A') }}
  when: result is defined